### PR TITLE
add mustache transformation to connection object

### PR DESCRIPTION
**Pull request by alexgv99**

### CODE REVIEW

**Comment by bestlong** [comment]
Hi @alexgv99 
I am not sure why this node needs mustache?

**Comment by alexgv99** [comment]
Hi... it's a way to change connection strings between environments... for instance, in my case, we have databases for tests and production... each one in a different server. Using a mustache template we can replace parts of the connection strings with environment variables, pointing to the correct server in each of them.

**Comment by bestlong** [comment]
Okay, i get it.

please also update src/mssql.html add help text before `data-template-name="MSSQL-CN"`. like:

```
<script type="text/x-red" data-help-name="MSSQL-CN">
    <p>Config node for Node-RED to MS SQL</p>
    <h4>Connection setup</h4>
    <p>You can uses the <i><a href="http://mustache.github.io/mustache.5.html" target="_new">mustache</a></i> format.</br>
    Example: <i>{{{environment variable name}}}</i></p>
</script>
```

**Comment by alexgv99** [comment]
As asked.

**Comment by alexgv99** [comment]
Done, as you asked for. I hope it's OK.

**Pull request merged**
