### PR TITLE
Update depenedencies and linting

### PR DESCRIPTION
**Pull request by Steve-Mcl**
* Updates to latest MSSQL 10.x stream
  * I have avoided switching to 11.x stream in this PR as it bumps Node requirement up to v18 minimum!
  * This is someting that will need to be discussed.
* Remove some eslint overrides to be closer to eslint:recomended 
  * fix up resulting ESLINT errors

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@bestlong Thank you for fixing the CI runner - Tests are now passing.

This PR updates linting on files closer to eslint _standard_ 
Also, it updates the CI to run lint as part of the test.

Note I also added Node v20 into the matrix.

All this gets rid of a few npm audit high priorities.

---

At some later time we should discuss how best to move to the MSSQL 11.x stream. 
That will require Node v18 as minimum but that will break many legacy Node-RED installations (like where Node-RED is built into a hardware device with older, non maintained Firmware).
I realise this is not "our" problem but we should be mindful and not break things for folk who have no choice (if we can avoid it).

**Comment by bestlong** [comment]
Hi @Steve-Mcl 

No problem, the part that I think must be dealt with has been completed, and it’s up to you to do the rest.

**Comment by Steve-Mcl** [comment]
@bestlong ok, thanks.

If you could review and approve when you get time that would be great.

**Review by bestlong — APPROVED** [review]
LGTM.

**Pull request merged**
